### ISSUE TITLE
Hamming Window in ver.1.1.3

### ISSUE THREAD

**Issue by unitay** [swharden/FftSharp#44]
Why Cosine, Hamming, Tukey and Welch windows is internal? Why Window.NormalizeInPlace is internal? How to use this in inherited class?

**Comment by swharden** [comment]
Hi @unitay, 

Making those windows `internal` was not intentional. I'll make them `public` and issue a new release tonight. 

I'm curious - what functionality are you adding by inheriting/extending these classes? These classes are pretty simple (e.g., [Hamming.cs](https://github.com/swharden/FftSharp/blob/master/src/FftSharp/Windows/Hamming.cs)) so I'm interested in learning more about your use case.
